### ISSUE TITLE
Can't "jog" after setting Workspace Origin

### ISSUE THREAD

**Issue by robwaldhauser** [noobydp/CNC-Macros#2]
First off, thank you for your work on this, it's tremendous and usable as is! There were a few things I had to tweak I'm happy to share as well in a pull request once I understand everything and get some use with it.

One noticeable issue I have is trying to job the toolhead around after setting workspace. If I use the jogging controls in Mainsail, it will take the number that displays in Mainsail and seemingly add it to the workspace offset as a relative move (which sends things crashing).

I was able to write a macro to wiggle around this for the few movements I need (for instance, moving Z to a safe distance after setting workspace home so I can turn the router on) but do you see any way of changing that behavior or am I using something incorrectly?

Cheers!
Rob

discord username is xberty if you want to chat about this project

**Comment by noobydp** [comment]
Oh yeah I forgot about that problem 😭

I'll see if I can figure out a solution. 

There are two temp solutions:
1. Set the offset to 0 for the axis you're jogging (I usually do this for Z when I do a tool change because the old offset isn't relevant). You can use the update offset macro and leave X Y blank to only update one axis. 

2. Type in the move value into the text inputs instead of jog. 
This one isn't obvious, but if you enter X=10 in the text box, it will move the toolhead to 10+offset.

**Comment by robwaldhauser** [comment]
Yeah dang near cut my clamp in two pieces by accident haha.

Number 1 I don't love because then I lose where my offset was, but number 2 is what I ended up doing in a way, just through a macro for raising Z. I'll take a look under the hood as well to see if I can think of a crafty way of making those buttons work for us post setting workspace!

**Comment by noobydp** [comment]
I've created a new branch for the fix, but I havent tested it yet: #manualjoggingfix
I'll try to do some work reviewing & testing over the next couple of days.
